[package]
name = "afl"
version = "0.12.0"
readme = "README.md"
license = "Apache-2.0"
authors = ["Keegan McAllister <mcallister.keegan@gmail.com>",
           "Corey Farwell <coreyf@rwell.org>"]
description = "Fuzzing Rust code with american-fuzzy-lop"
repository = "https://github.com/rust-fuzz/afl.rs"
homepage = "https://github.com/rust-fuzz/afl.rs"
edition = "2018"

[build-dependencies]
xdg = "2.1"
rustc_version = "0.4"

[dependencies]
cc = "1.0"
clap = { version = "3.0", features = ["cargo"] }
libc = "0.2.117"
rustc_version = "0.4"
xdg = "2.1"
lazy_static = { version = "1.4.0", optional = true }

[dev-dependencies]
tempfile = "3"

[features]
reset_lazy_static = ["lazy_static"]
